global:
scrape_interval: 15s


scrape_configs:
- job_name: 'nomad'
static_configs:
- targets: ['nomad-server-1:4647', 'nomad-client-1:4647']
metrics_path: /metrics


- job_name: 'n8n'
metrics_path: /metrics
static_configs:
- targets: ['<n8n-host>:5678']